server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://pitchnest-backend-10489410829.us-central1.run.app/api/;
        proxy_set_header Host pitchnest-backend-10489410829.us-central1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}
