"""add pitch_name to pitches

Revision ID: 4ec7a62fdc07
Revises: 72d6204b24f1
Create Date: 2026-03-12 00:24:30.354984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec7a62fdc07'
down_revision: Union[str, Sequence[str], None] = '72d6204b24f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_members',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.add_column('pitches', sa.Column('pitch_name', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_pdf_url', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('startup_type', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('room_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'room_id')
    op.drop_column('pitches', 'experience_level')
    op.drop_column('pitches', 'startup_type')
    op.drop_column('pitches', 'industry')
    op.drop_column('pitches', 'pitch_pdf_url')
    op.drop_column('pitches', 'pitch_name')
    op.drop_table('room_members')
    op.drop_table('chat_messages')
    op.drop_table('rooms')
    # ### end Alembic commands ###
